# Generated by Django 4.1.13 on 2024-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation_text')},
        ),
    ]
